### ISSUE TITLE
Serverrules overhaul & Forum Post

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/PMP-Liberation#1]
The Serverrules should be overhauled and integrated into https://www.killahpotatoes.de/index.php?board/203-public-milsim-project/

**Comment by Dubjunk** [comment]
Overhauled Example:

§1 Verhalten auf dem Server:
1. Das taktisch orientierte Spielen und der Spielspaß steht an erster Stelle
2. Behandelt andere Mitspieler mit Respekt und benutzt eine Höfliche Umgangsform
3. Rassistische sowie diskriminierende Äußerungen sind untersagt und werden nicht toleriert
4. Das Einspielen nicht immersiver Geräusche ist zu unterlassen, eine angemessene Geräuschkulisse gilt zu wahren
5. Alleingänge sind zu unterlassen 
6. Nach schwerem regelwidrigem Verhalten wird der entsprechende Spieler verwarnt und ggf. vom Spiel ausgeschlossen
7. Teambeschuss (Blue on Blue) ist zu vermeiden

§2 Verhalten in der Base/FOB:
1. Es gilt eine angemessene Lautstärke einzuhalten um aktive Truppenteile nicht zu stören
2. Fahrzeuge sollten adäquat genutzt werden
3. Die eigene Waffe ist zu sichern und/oder zu Holstern bzw. auf dem Rücken zu platzieren
4. Waffengebrauch innerhalb einer FOB ist nur bei Verteidung dieser gestattet
5. Die Ausrüstung darf größtenteils frei gewählt werden, lediglich die zu tragende Waffenart (Sturmgewehr, Maschinengewehr usw.) dürfen durch Zug-/Gruppen-/Truppführung vorgegeben werden

§3 Einsatzbereitschaft:
1. Vor dem ausrücken ist die Erreichbarkeit via Funk zu gewährleisten
2. Der jeweilige Zug-/Gruppen-/Truppführer muss seinen Gruppennamen wie folgt benennen, die eingeklammerten Daten sind zusätzliche Funkgeräte:
""Rufname"" | ""Funkgerät"" - ""Kanal"" (| ""Funkgerät"" - ""Kanal"")
Beispiel: Thor | 52 - K01 (| 117F - K02)
3. Trupps müssen immer mit mindestens 2 Personen besetzt sein
4. Jeder Trupp muss über mindestens ein Langstrecken Funkgerät (AN/PRC-152 oder AN/PRC-117F) erreichbar sein
5. Luftnahunterstützung (CAS) ist nur in Verbindung mit einem Fliegerleitoffizier (FAC, JTAC o.ä.) zugelassen

§4 Führungs- und Fernmeldewesen:
1. Der jeweilige Zug-/Gruppen-/Truppführer ist für die Disziplin seiner Einheit verantwortlich und dient als Ansprechpartner für die nächsthöhere Einheit bzw. das Serverteam
2. In den LR Kanälen 01-10 gilt es eine Funkdisziplin einzuhalten, für den Truppinternen Funk ist der jeweilige Zug-/Gruppen-/Truppführer verantwortlich

§5 Fahrzeuge:
1. Mitgenommene Fahrzeuge sollten wieder zum FOB zurückgeführt werden
2. Eine Fahrzeugbesatzung muss mindestens aus 2 Soldaten bestehen (z.B. Kraftfahrer und Richtschütze bzw. Pilot und Co-Pilot)
3. Beschädigte Fahrzeuge sollten zur FOB zurückverlegt werden, dies ist über einen Transport via Heli oder eine Bergung zu realisieren
4. Die Benutzung vom Kampfpanzern oder Kampfhelikoptern bedarf der Freigabe eines Zug- oder Kontingentsführers

§6 Liberation Mod:
1. Mutwillige Zerstörung von zivilen Fahrzeugen und Gebäuden ist verboten
2. Das töten von Zivilisten ist verboten
3. Ressourcen sind mit Bedacht einzusetzen 


Das Serverteam behält sich vor, das Regelwerk anzupassen, sollte die Notwendigkeit gegeben sein.

**Comment by Sim0nRiley** [comment]
Think this Issue could be closed. In my oppenion we can realize this rules

**Comment by Dubjunk** [comment]
Final version:

§1 Verhalten auf dem Server:

1. Das taktisch orientierte Spielen und der Spielspaß steht an erster Stelle
2. Behandelt andere Mitspieler mit Respekt und benutzt eine Höfliche Umgangsform
3. Rassistische sowie diskriminierende Äußerungen sind untersagt und werden nicht toleriert
4. Das Einspielen nicht immersiver Geräusche ist zu unterlassen, eine angemessene Geräuschkulisse gilt zu wahren
5. Alleingänge sind zu unterlassen
6. Nach schwerem regelwidrigem Verhalten wird der entsprechende Spieler verwarnt und ggf. vom Spiel ausgeschlossen
7. Teambeschuss (Blue on Blue) ist zu vermeiden

§2 Verhalten in der Base/FOB:

1. Es gilt eine angemessene Lautstärke einzuhalten um aktive Truppenteile nicht zu stören
2. Fahrzeuge sollten adäquat genutzt werden
3. Die eigene Waffe ist zu sichern und/oder zu Holstern bzw. auf dem Rücken zu platzieren
4. Waffengebrauch innerhalb einer FOB ist nur bei Verteidung dieser gestattet
5. Die Ausrüstung darf größtenteils frei gewählt werden, lediglich die zu tragende Waffenart (Sturmgewehr, Maschinengewehr usw.) dürfen durch Zug-/Gruppen-/Truppführung vorgegeben werden

§3 Einsatzbereitschaft:

1. Vor dem ausrücken ist die Erreichbarkeit via Funk zu gewährleisten
2. Der jeweilige Zug-/Gruppen-/Truppführer muss seinen Gruppennamen wie folgt benennen, die eingeklammerten Daten sind zusätzliche Funkgeräte:
""Rufname"" | ""Funkgerät"" - ""Kanal"" (| ""Funkgerät"" - ""Kanal"")
Beispiel: Thor | 52 - K01 (| 117F - K02)
3. Trupps müssen immer mit mindestens 2 Personen besetzt sein
4. Jeder Trupp muss über mindestens ein Langstrecken Funkgerät (AN/PRC-152 oder AN/PRC-117F) erreichbar sein
5. Luftnahunterstützung (CAS) ist nur in Verbindung mit einem Fliegerleitoffizier (FAC, JTAC o.ä.) oder durch Freigabe eines Zugführers zugelassen

§4 Führungs- und Fernmeldewesen:

1. Der jeweilige Zug-/Gruppen-/Truppführer ist für die Disziplin seiner Einheit verantwortlich und dient als Ansprechpartner für die nächsthöhere Einheit bzw. das Serverteam
2. In den LR Kanälen 01-10 gilt es eine Funkdisziplin einzuhalten, für den Truppinternen Funk ist der jeweilige Zug-/Gruppen-/Truppführer verantwortlich

§5 Fahrzeuge:

1. Mitgenommene Fahrzeuge sollten wieder zum FOB zurückgeführt werden
2. Eine Fahrzeugbesatzung muss mindestens aus 2 Soldaten bestehen (z.B. Kraftfahrer und Richtschütze bzw. Pilot und Co-Pilot)
3. Beschädigte Fahrzeuge sollten zur FOB zurückverlegt werden, dies ist über einen Transport via Heli oder eine Bergung zu realisieren
4. Die Benutzung vom Kampfpanzern oder Kampfhelikoptern bedarf der Freigabe eines Zug- oder Kontingentsführers

§6 Liberation Mod:

1. Mutwillige Zerstörung von zivilen Fahrzeugen und Gebäuden ist verboten
2. Das töten von Zivilisten ist verboten
3. Ressourcen sind mit Bedacht einzusetzen


Das Serverteam behält sich vor, das Regelwerk anzupassen, sollte die Notwendigkeit gegeben sein.
