### ISSUE TITLE
AI kiling people on pre-spawn

### ISSUE THREAD

**Issue by Hill3234** [KillahPotatoes/PMP-Liberation#10]
add a function/module that kills / deletes all enemys within 1km around the pre-spawn area,

**Comment by Hill3234** [comment]
Editor, F5(Systeme), Sontiges, Modul: Zonenbeschränkung

benötigt allerdings ein Skript das dann die Feindeinheiten mit dem Modul synchronisiert sobald sie an die Zone kommen.

Gibt da aber sicher auch eine einfachere Lösung.

**Comment by Hill3234** [comment]
Eventuell auch durch einen trigger mit selben Radius wie das Modul möglich, der bei betreten auslöst und dann die Einheiten weiter gibt. // müsste dann aber auf wiederholbar gesetzt werden

**Comment by Wyqer** [comment]
```sqf
// Endlosschleife
while {true} do {
    {
        // Gehe über alle Einheiten. Wenn die Einheit nicht Blufor und näher als 200m am Spawn marker ist, dann lösche sie.
        if ((side group _x != GRLIB_side_friendly) && (_x distance (getMarkerPos GRLIB_respawn_marker) < 200)) then {
            deleteVehicle _x;
        };
    } forEach allUnits;

    // Warte ~30 Sekunden
    sleep 30;
};
```

**Comment by Hill3234** [comment]
Sieht gut aus :)
