### ISSUE TITLE
Spawnticket System?

### ISSUE THREAD

**Issue by Sim0nRiley** [KillahPotatoes/PMP-Liberation#15]
I have toughts about a Ticket system for Spawn/Death to Stop the Respawn abuse and the Vehicle abuse on Liberation. The Supply Price and amounts will unfortunaly not Stop still the abuse from the Players. 
The Players should learn in my oppinion more responsibility

**Comment by Hill3234** [comment]
seems like halo timer Adjustment to 30min fixed this for now.
