### ISSUE TITLE
Logistic Optional Whitelist 

### ISSUE THREAD

**Issue by Sim0nRiley** [KillahPotatoes/PMP-Liberation#16]
Independently from the CAS Withelist, we schould think about a "Light" possibility to fly an Logistic Chopper independently from the played Hours (actually 75hrs.) on the Server. 
We need definitly more Logistic Pilots.

**Comment by Dubjunk** [comment]
I would deny this suggestion, if we enable logistic choppers for everyone there will be no more convois and there would be too much resources avaiable.
I think it would influence the gameplay very negative.
Helicopters are rare and something special, that would be lost.
