### ISSUE TITLE
Vehicle price rework

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/PMP-Liberation#18]
The vehicle prices need to be reworked and the ressource production needs to be decreased.

**Comment by Hill3234** [comment]
https://docs.google.com/spreadsheets/d/1lZY7HZZf1Z0zKo2SlmDEhfjcm-L2ONqI9nLjs7igmNU/edit?usp=sharing

not 100% complete, but tried to include even size of armament.

**Comment by Dubjunk** [comment]
I will rework the chart later, gonna implement some sorting mechanisms for a better overview and some other improvements

**Comment by Dubjunk** [comment]
I reworked the chart and implemented an page to configure the data (pricing, factions etc.)
The File should be downloaded and used with Excel for a better handling.
https://drive.google.com/open?id=1GmDVX8wLk4UiaMHA75SawQrIgZR0fHua

**Comment by Sim0nRiley** [comment]
Think both version are good, lets pick up the best of both version

**Comment by Dubjunk** [comment]
Updated Version!

https://drive.google.com/open?id=1GmDVX8wLk4UiaMHA75SawQrIgZR0fHua

Added:
- 1. Supply factor for "remote weapon stations" (ex. FLW100)
- 2. Ammo factor for "bad optics" (like most russian vehicles have)
- 3. Fuel factor for "fuel-guzzlers" (for trucks and tanks)
- 4. 155mm caliber
- 5. Tier description and examples (WiP)

Changed:
- Supply basic value to 2000
