### ISSUE TITLE
should we remove the vanilla at launcher?

### ISSUE THREAD

**Issue by Hill3234** [KillahPotatoes/PMP-Liberation#22]
after some live testing and observing, it seems that it is just too broken for the current liberation mission.

so we could remove the mk1, which has its rangefinder
or we can even remove the mk0 too, because for its weight, it has too many shots with too much power.

**Comment by Sim0nRiley** [comment]
Think this Suggestion is not so good, cause we have to little on Multi-Shot Launchers at Arsenal. Its better to Remove the Titan Launchers and Vanilla RPG-7
