### ISSUE TITLE
Public Statement about the Situation between PMP and A3MC

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/PMP-Liberation#3]
We need to clear the Situation in the ArmA 3 MilSim Community about the latest Events and our Intention

**Comment by Sim0nRiley** [comment]
Statement zur Entzweiung des A3MC Projekts hin zum Public MilSim Project.

Sehr geehrte Community, 

aufgrund der aktuellen Veränderungen wollen wir nochmal ein Sitrep zur aktuellen Situation liefern.
Aufgrund bestimmter unstimmigkeiten und unterschiedlicher Zielsetzungen hat sich der großteil der mitentwickelnden Spieler dazu entschieden sich vom A3MC Projekt loszulösen und den Server in ein neues Projekt zu überführen.
Aktuell nutzen wir sehr dankbar die Plattform der Killahpotatoes, sei es Gameserver aber auch Forum und Discord zur Kommunikation, an dieser Stelle nochmal vielen Dank an das KP-Team und der Community für die Unterstützung.
Von unserer Seite aus sind beide Parteien recht friedlich auseinander gegangen und jeder wird sein Projekt getrennt von einander fortsetzen. Für das neue Public MilSim Project steht für uns immernoch die weiterentwicklung und nutzung der Liberation an erster stelle.
Deswegen freuen wir uns auch weiterhin über die Zahlreichen Spieler auf unserem Server und wenn ihr Feedback geben wollte, könnt ihr dies gern über das KP-Forum tun oder aber auch über Discord. 

Mit besten Grüßen, euer Public MilSim Project Team

**Comment by Dubjunk** [comment]
https://www.facebook.com/groups/353350415063260/permalink/494507837614183/
