### ISSUE TITLE
zsu-tigris cockoff and framedrop

### ISSUE THREAD

**Issue by Hill3234** [KillahPotatoes/PMP-Liberation#39]
zsu tigris ace cockoff causes hard frame drops.

solution:

1. Disabling / Enabling Cook off for individual vehicles
You can dynamically enable and/or disable vehicle cook off for individual vehicles by using setVariable:

VEHICLE setVariable ["ace_cookoff_enable", true, true];
The above will enable cook off for that specific vehicle, no matter the mission settings.

Likewise, cook off can also be disabled for a specific vehicle:

VEHICLE setVariable ["ace_cookoff_enable", false, true];

**Comment by Dubjunk** [comment]
ZSU temporary disabled
