### ISSUE TITLE
Update server modset

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/PMP-Liberation#5]
The Server Modset needs to be overhauled and published

**Comment by Hill3234** [comment]
my pref on Second Suggestion,

Gref units as possible enemy, -> units do have body armor
and it does not need Project Opfor -> where units don't have armors

clear state: RHSGREF > Project Opfor  in terms of use.

**Comment by Dubjunk** [comment]
**Like this??? :**

Needed Mods
- 3CB BAF Weapons (?)
- 3CB BAF Weapons ACE Compat (?)
- ACE3
- ACRE2
- ADV ACE CPR (ADV ACE MEDICAL?)
- BWMod
- BWMod ACE Compat
- CBA A3
- Enhanced Movement
- Military Gear Pack
- Redd'n'Tank Vehicles
- RHSAFRF
- RHSAFRF ACE Compat
- RHSGREF
- RHSGREF ACE Compat
- RHSUSAF
- RHSUSAF ACE compat

Optional Mods
- DynaSound 2
- Achilles

Maybe there could be added some two seated Jets for CAS?!

**Comment by Hill3234** [comment]
looks great!

**Comment by Sim0nRiley** [comment]
Great Suggestion for the Jets!

**Comment by Sim0nRiley** [comment]
We forget the Lythium Map and JBAD Buildings in the current settings!

**Comment by Sim0nRiley** [comment]
The question is, is it still possible with the Jets? Still have some problems with the Steam Key query?

**Comment by Dubjunk** [comment]
So the final Modset could be:

Needed Mods
- 3CB BAF Weapons (?)
- 3CB BAF Weapons ACE Compat (?)
- ACE3
- ACRE2
- ADV ACE CPR (ADV ACE MEDICAL?)
- BWMod
- BWMod ACE Compat
- CBA A3
- Enhanced Movement
- F-15 Eagle
- F-16 Fighting Falcon
- FIR AWS
- JBAD Buildings
- Lythium
- Military Gear Pack
- Redd'n'Tank Vehicles
- RHSAFRF
- RHSAFRF ACE Compat
- RHSGREF
- RHSGREF ACE Compat
- RHSUSAF
- RHSUSAF ACE compat

Optional Mods
- DynaSound 2
- Achilles

I would work without the F-14, because the F-15 and F-16 could be used better for CAS and Air supremacy

**Comment by Sim0nRiley** [comment]
Yes, thats ok for me. But much Players love the F-14 Tomcats as an "Prestige Objekt", flights and handles very lovely. Let them have the Fun with this Jet. And for CAS Listing and Training Units? Nothing better than this. I think this Jets makes very much People happy ;)

**Comment by Dubjunk** [comment]
I think 3 Jet Mods are too much so we need to kick one of them

**Comment by Sim0nRiley** [comment]
So than... R.i.P F-14 Tomcat ;(

**Comment by Dubjunk** [comment]
Final List:

Needed Mods
- 3CB BAF Weapons
- 3CB BAF Weapons ACE Compat
- ACE3
- ACRE2
- ADV ACE CPR
- BWMod
- BWMod ACE Compat
- CBA A3
- Enhanced Movement
- F-14 Tomcat
- F-15 Eagle
- F-16 Fighting Falcon
- FIR AWS
- JBAD Buildings
- Lythium
- Military Gear Pack
- Redd'n'Tank Vehicles
- RHSAFRF
- RHSAFRF ACE Compat
- RHSGREF
- RHSGREF ACE Compat
- RHSUSAF
- RHSUSAF ACE compat

Serverside Mods
- Advanced Rappeling
- Advanced Sling Loading
- Advanced Towing

Optional Mods
- Achilles
- DynaSound 2
- ZEC
