### ISSUE TITLE
FOB attacks while low players/afks on public server

### ISSUE THREAD

**Issue by Hill3234** [KillahPotatoes/PMP-Liberation#9]
FOB attacks are too hard for public servers that run 24/7 and have times with low players.

fix could be to add an option to disable fob attacks (maybe for the commander)

or what i do prefere would be to add a min. player count what is need to getting an fob attack happening

some like: if playercount >= 5 disable attacks on fob [else] allow attacks

**Comment by Dubjunk** [comment]
Otherwise as disabling the AI attacks on a certain player count, we could activate the BLUFOR defenders until there are x players on the Server

**Comment by Hill3234** [comment]
good idea.

**Comment by Hill3234** [comment]
done.
